apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeconfig-generator
subjects:
- kind: ServiceAccount
  name: kubeconfig-generator
  namespace: kubegen
roleRef:
  kind: ClusterRole
  name: kubeconfig-generator
  apiGroup: rbac.authorization.k8s.io
