apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeconfig-generator
rules:
- apiGroups: [""]
  resources: ["serviceaccounts", "namespaces"]
  verbs: ["get", "create", "list"]
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
- apiGroups: ["oauth.openshift.io"]
  resources: ["oauthaccesstokens"]
  verbs: ["create"]
