apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubegen

resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap.yaml
- deployment.yaml
- route.yaml
- service.yaml
- serviceaccount.yaml
